RubyOnRails(GroupAssignment)/ekrequilt_web_store/config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  ActiveAdmin.routes(self)

  unless Rails.env.production?
    get 'design' => 'design#index'
  end

  resources :contact, only: [:new, :create]

  resources :users, only: :show

  resources :newsletters, only: [:create, :destroy] do
    post 'deliver', on: :new
  end

  resources :products, only: [:index, :show]

  resources :line_items, only: :create

  resources :carts, as: :user_cart, only: [:show, :destroy]

  resources :orders, only: [:show, :create, :new, :destroy] do
    get 'express', on: :new
  end

  devise_for :admin_accounts, controllers: { sessions: 'admin_users_sessions'}

  devise_for :accounts,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             confirmations: 'confirmations',
                             registrations: 'registrations',
                             sessions: 'users_sessions',
                             passwords: 'passwords' ,
                             unlocks: 'unlocks' }

  devise_scope :account do
    put 'accounts/confirmation/confirm', to: 'confirmations#confirm'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'welcome#index'
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/controllers/users_sessions_controller.rb
class UsersSessionsController < Devise::SessionsController
  after_filter :set_csrf_headers, only: [:create, :destroy]
  respond_to :js

  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end

  def create
    self.resource = warden.authenticate(auth_options)

    if resource && resource.active_for_authentication?
      set_flash_message(:notice, :signed_in)
      sign_in(resource_name, resource)

      destroy_guest
      yield resource if block_given?
    else
      message = warden.message || default || :unauthenticated

      flash.keep(:alert)
      flash[:alert] = I18n.t(:"#{resource_name}.#{message}", scope: 'devise.users_sessions.')
    end

    respond_with resource, location: after_sign_in_path_for(resource)
  end

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out
    yield if block_given?

    current_user # initialize guest user

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :destroy }
    end
  end

  protected

  def set_csrf_headers
    if request.xhr?
      response.headers['X-CSRF-Token'] = form_authenticity_token
    end
  end

  private

  def destroy_guest
    if User.find(session[:guest_user_id])
      guest = User.find(session[:guest_user_id])
      guest_cart = guest.cart
      current_user.cart.add_line_items(guest_cart)
      guest.destroy
      session[:guest_user_id] = nil
    end
  end
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/_form.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
    <div id="js-message" class="forms large-8 large-centered columns"></div>
    <fieldset>
      <legend><%= t('devise.login') %></legend>

      <div class="row">
        <div class="large-12 columns">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: 'off' %>
        </div>
      </div>

      <% if devise_mapping.rememberable? -%>
          <div class="row">
            <div class="large-12 columns">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          </div>
      <% end -%>

      <div class="row">
        <div class="large-12 columns">
          <%= f.submit t('devise.login'), class: 'small button' %>
        </div>
      </div>
    </fieldset>
<% end %>

<%= render 'devise/shared/links' %>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/_sign_in_modal.html.erb
<div id="sign-in-modal" class="reveal-modal forms large-12 large-centered columns" data-reveal>

</div>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/create.js.erb
<% if account_signed_in? %>
    $('#sign-in-modal').foundation('reveal', 'close');

    $(document).ajaxComplete(function(event, xhr, settings) {
        var csrf_token = xhr.getResponseHeader('X-CSRF-Token');

        if (csrf_token) {
            $('meta[name="csrf-token"]').attr('content', csrf_token);
        }
    });

    <%= render partial: 'layouts/status' %>
<% else %>
    $('#js-message').html("<%= escape_javascript(render partial: 'layouts/messages') %>");
<% end %>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/destroy.js.erb
$('#main_window').html("<%= escape_javascript(render partial: 'welcome/index') %>");
<%= render partial: 'layouts/status' %>

$(document).ajaxComplete(function(event, xhr, settings) {
    var csrf_token = xhr.getResponseHeader('X-CSRF-Token');

    if (csrf_token) {
        $('meta[name="csrf-token"]').attr('content', csrf_token);
    }
});

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/new.html.erb
<%= render partial: 'form' %>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/users_sessions/new.js.erb
$('#sign-in-modal').html("<%= escape_javascript(render partial: 'form', locals: { resource: resource }) %>").foundation('reveal', 'open');