RubyOnRails(GroupAssignment)/ekrequilt_web_store/config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  ActiveAdmin.routes(self)

  unless Rails.env.production?
    get 'design' => 'design#index'
  end

  resources :contact, only: [:new, :create]

  resources :users, only: :show

  resources :newsletters, only: [:create, :destroy] do
    post 'deliver', on: :new
  end

  resources :products, only: [:index, :show]

  resources :line_items, only: :create

  resources :carts, as: :user_cart, only: [:show, :destroy]

  resources :orders, only: [:show, :create, :new, :destroy] do
    get 'express', on: :new
  end

  devise_for :admin_accounts, controllers: { sessions: 'admin_users_sessions'}

  devise_for :accounts,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             confirmations: 'confirmations',
                             registrations: 'registrations',
                             sessions: 'users_sessions',
                             passwords: 'passwords' ,
                             unlocks: 'unlocks' }

  devise_scope :account do
    put 'accounts/confirmation/confirm', to: 'confirmations#confirm'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'welcome#index'
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_filter :authenticate_admin_account!, only: [:deliver]
  before_filter :authenticate_account!, only: [:create, :destroy]

  def deliver
    NewsletterMailer.news_broadcast(params[:content]).deliver_now

    flash[:notice] = I18n.t('newsletter_sent')
    redirect_to store_manager_root_path
  end

  def create
    @user.subscribed_newsletter = true
    @user.save

    redirect_to user_path(@user)
  end

  def destroy
    @user.subscribed_newsletter = false
    @user.save

    redirect_to user_path(@user), status: 303
  end
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/store_manager/newsletter/_newsletter_form.erb
<%= form_tag(deliver_new_newsletter_path, method: :post, html: {class: 'forms'}) do |f| %>
    <fieldset>
      <div class="row">
        <div class="large-12 columns">
          <%= label_tag :content, t('mailer.contact_content')  %><br />
          <%= text_area_tag :content, nil, rows: 50 %>
        </div>
      </div>

      <div class="large-12 columns">
        <%= submit_tag t('send'), class: 'button small success' %>
      </div>
    </fieldset>
<% end %>