RubyOnRails(GroupAssignment)/ekrequilt_web_store/config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  ActiveAdmin.routes(self)

  unless Rails.env.production?
    get 'design' => 'design#index'
  end

  resources :contact, only: [:new, :create]

  resources :users, only: :show

  resources :newsletters, only: [:create, :destroy] do
    post 'deliver', on: :new
  end

  resources :products, only: [:index, :show]

  resources :line_items, only: :create

  resources :carts, as: :user_cart, only: [:show, :destroy]

  resources :orders, only: [:show, :create, :new, :destroy] do
    get 'express', on: :new
  end

  devise_for :admin_accounts, controllers: { sessions: 'admin_users_sessions'}

  devise_for :accounts,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             confirmations: 'confirmations',
                             registrations: 'registrations',
                             sessions: 'users_sessions',
                             passwords: 'passwords' ,
                             unlocks: 'unlocks' }

  devise_scope :account do
    put 'accounts/confirmation/confirm', to: 'confirmations#confirm'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'welcome#index'
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr>
    <p>© Ekrequilt | <%= link_to t('mailer.contact_us'), new_contact_path, remote: true %></p>
  </div>
</footer>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <hr>
    <div class="category">
      <div class="category_smallScreen">
        <%= link_to '#categoryExpand' do %>
            Category
            <!--<%= image_tag 'http://alexandstein.com/resources/images/icons/hamburger.png', alt: 'Menu', height: 60, width: 60 %>-->
        <% end %>
      </div>
      <div class="large-12 columns">
        <nav class="top-bar">
          <section class="top-bar-section" data-topbar data-options="navigation">

            <ul class="right">
              <% ProductCategory.all.each do |pc| %>
                  <li>
                    <%= link_to products_path(category: pc.id), remote: true do %>
                        <span class="link-border-bottom"><%= pc.name %></span>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </section>
        </nav>
      </div>
    </div>
    <br/>
    <br/>
    <hr>
  </div>
</header>

<div class="contain-to-grid fixed">
  <nav class="top-bar-stuff" data-topbar data-options="sticky_on: large" role="navigation">
    <div class="logo-details">
      <%= link_to root_path, id: 'logo', remote: true do %>
          <%= image_tag 'http://globalplanit.ca/wp-content/uploads/2013/06/client-logo-placeholder.png' %>
      <% end %>
    </div>

    <div class="search-form-search">
      <%= form_tag products_path, class: 'form-inline', id: 'search-field', method: :get, remote: true do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search stuffs' %>
          <input type="submit" value="Search" class="action-btn accent-text" name="submit" id="search-submit">
      <% end %>
    </div>

    <div class="menu">
      <div class="menuIcon">
        <%= link_to '#menuExpand' do %>
            <%= image_tag 'http://alexandstein.com/resources/images/icons/hamburger.png', alt: 'Menu', height: 60, width: 60 %>
        <% end %>
      </div>
      <div id="status_buttons" class="links">
        <%= render partial: 'layouts/status_buttons' %>
      </div>
    </div>
  </nav>
</div>

<%= render partial: 'users_sessions/sign_in_modal' %>

<div id="message" class="forms large-8 large-centered columns">
  <% if controller.request.format.html? %>
      <%= render partial: 'layouts/messages' %>
  <% end %>
</div>


</div>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_messages.html.erb
<% if notice %>
  <div data-alert class="alert-box radius notice"><%= notice %></div>
  <% flash.delete(:notice) %>
<% end %>

<% if alert %>
  <div data-alert class="alert-box alert round alert"><%= alert %></div>
  <% flash.delete(:alert) %>
<% end %>

<%= devise_error_messages! %>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_modal_status.js.erb
$('#status_buttons').html("<%= escape_javascript(render partial: 'layouts/status_buttons') %>");
$('#js_message').html("<%= escape_javascript(render partial: 'layouts/messages') %>");

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_status.js.erb
$('#status_buttons').html("<%= escape_javascript(render partial: 'layouts/status_buttons') %>");
$('#message').html("<%= escape_javascript(render partial: 'layouts/messages') %>");

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/_status_buttons.html.erb
<ul>
  <% if !admin_account_signed_in? && controller_name != 'carts' %>
      <li>
        <%= link_to t('cart.name') + " (#{@user.cart.line_items_count})", user_cart_path(@user.id), id: 'cart-link', class: 'small button success radius', remote: true %>
      </li>
  <% end %>
  <% if account_signed_in? || admin_account_signed_in? %>
      <% if admin_account_signed_in? %>
          <li>
            <% if current_admin_account.role?(:admin) %>
                <%= link_to t('admin_page'), admin_dashboard_path, class: 'small button success radius' %>
            <% else %>
                <%= link_to t('store_manager_page'), store_manager_dashboard_path, class: 'small button success radius' %>
            <% end %>
          </li>
      <% else %>
          <li>
            <%= link_to t('mypage'), user_path(@user.id), class: 'small button success radius', remote: true %>
          </li>
      <% end %>
      <li>
        <%= link_to t('devise.log_out'), destroy_account_session_path, class: 'small button success radius', method: :delete, remote: true %>
      </li>
  <% else %>
      <% if controller_name != 'admin_users_sessions' %>
          <li>
            <%= link_to t('devise.login'), new_account_session_path, class: 'small button success radius', remote: true %>
          </li>
      <% end %>
  <% end %>
</ul>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Ekrequilt</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<%= render partial: 'layouts/header' %>
<section id="main_window">
  <%= yield %>
</section>
<%= render partial: 'layouts/footer' %>

<script>
    $(document).foundation();
    $(document).on('close.fndtn.reveal', '#sign-in-modal', function () {
        $('#sign-in-modal').html("");
    });

    $(function () {
        $("a[href=#menuExpand]").click(function (e) {
            $(".links").toggleClass("menuOpen");
            e.preventDefault();
        });
    });

    $(function () {
        $("a[href=#categoryExpand]").click(function (e) {
            $(".top-bar-section").toggleClass("menusOpen");
            e.preventDefault();
        });
    });
</script>
</body>
</html>