RubyOnRails(GroupAssignment)/ekrequilt_web_store/config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  ActiveAdmin.routes(self)

  unless Rails.env.production?
    get 'design' => 'design#index'
  end

  resources :contact, only: [:new, :create]

  resources :users, only: :show

  resources :newsletters, only: [:create, :destroy] do
    post 'deliver', on: :new
  end

  resources :products, only: [:index, :show]

  resources :line_items, only: :create

  resources :carts, as: :user_cart, only: [:show, :destroy]

  resources :orders, only: [:show, :create, :new, :destroy] do
    get 'express', on: :new
  end

  devise_for :admin_accounts, controllers: { sessions: 'admin_users_sessions'}

  devise_for :accounts,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                             confirmations: 'confirmations',
                             registrations: 'registrations',
                             sessions: 'users_sessions',
                             passwords: 'passwords' ,
                             unlocks: 'unlocks' }

  devise_scope :account do
    put 'accounts/confirmation/confirm', to: 'confirmations#confirm'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'welcome#index'
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/models/cart.rb
class Cart < ActiveRecord::Base
  include Sellable
  belongs_to :user

  has_one :order, dependent: :destroy

  validates :user_id, presence: true

  def add_line_items guest_cart
    guest_cart.line_items.each do |item|
      increment_or_add_line_item(item)
    end

    guest_cart.drop_all_line_items
  end

  def line_items_count
    items = 0
    line_items.each { |item| items += item.quantity }
    items
  end

  def drop_all_line_items
    line_items.destroy_all
  end

  private

  def increment_or_add_line_item(item)
    line_item = LineItem.find_by_product_and_sellable(product: item.product, sellable: user.cart)

    if line_item
      line_item.quantity += item.quantity
      line_item.save
    else
      line_items << LineItem.create(product: item.product, sellable: user.cart, quantity: item.quantity)
    end
  end
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :customer?
  before_action :set_cart

  def show
  end

  def destroy
    @cart.drop_all_line_items

    render :show
  end

  private

  def customer?
    unless current_user.role?(:customer) || current_user.role?(:guest)
      raise CanCan::AccessDenied.new(I18n.t 'unauthorized.default', :read, Cart)
    end
  end

  def set_cart
    @cart = User.find(params[:id]).cart
    authorize! :show, @cart

    @line_items = @cart.line_items
  end
end

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/carts/_show.html.erb
<% 'Shopping Cart' %>
<section id="show_cart" class="forms large-5 large-centered columns">
  <fieldset>
    <% if @cart.price > 0 %>
        <table id="line_items">
          <tr>
            <th><%= t('cart.product') %></th>
            <th><%= t('cart.quantity') %></th>
            <th class="price"><%= t('cart.unit_price') %></th>
            <th class="price"><%= t('cart.full_price') %></th>
          </tr>
          <% for line_item in @line_items %>
              <tr class="<%= cycle :odd, :even %>">
                <td><%=h line_item.product.name %></td>
                <td class="qty"><%= line_item.quantity %></td>
                <td class="price"><%= line_item.product.price %> <%= t('cart.currency') %></td>
                <td class="fullprice"><%= line_item.price %> <%= t('cart.currency') %></td>
              </tr>
          <% end %>
          <tr>
            <td class="total price" colspan="4">
              <%= t('cart.total') + ' ' + @cart.price.to_s %> <%= t('cart.currency') %>
            </td>
          </tr>
        </table>

        <hr/>
        <div class="row">
          <div class="large-12 columns">
            <%= link_to t('empty_quiltbag'), user_cart_path, method: :delete, class: 'button small info', remote: true %> |
            <%= link_to t('continue_shopping'), products_path, class: 'button small info', remote: true %> |
            <%= link_to t('checkout'), new_order_path, class: 'button small success', remote: true %> |
            <%= link_to image_tag('https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif'), express_new_order_path %>
          </div>
        </div>
    <% else %>
        <div class="row large-12 columns large-centered">
          <h1><%= t('cart.no_line_items_in_cart')%></h1>
          <%= link_to t('continue_shopping'), products_path, class: 'button small success', remote: true %>
        </div>
    <% end %>
  </fieldset>
</section>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/carts/show.html.erb
<%= render partial: 'show' %>

RubyOnRails(GroupAssignment)/ekrequilt_web_store/app/views/carts/show.js.erb
$('#main_window').html("<%= escape_javascript(render partial: 'show', locals: { line_items: @line_items } ) %>");
<%= render partial: 'layouts/status' %>